### ISSUE TITLE
create packages so that directory structure has the following in src/main/java :

### ISSUE THREAD

**Issue by pmcder** [pmcder/demo-backend#1]
1. com.example.notes.entities
2. com.example.notes.services
3. com.example.notes.controllers

**Comment by ichervachidze** [comment]
Hi Patrick,
This directory already contains the following: 
![image](https://user-images.githubusercontent.com/73848270/146484622-119d32bf-8735-4324-aa80-aa87c228975f.png)
Just wanted to make sure if you want me to remove this.
This has DemoApplication class with the main class, so probably not?

**Comment by pmcder** [comment]
You can just delete that package.
